services:
  database:
    image: "postgres:16.0-alpine3.18"
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-local_db}
      POSTGRES_USER: ${POSTGRES_USER:-local_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-local_password}
    env_file:
      - ../.env.development
    ports:
      - "5432:5432"
